apiVersion: 1
contactPoints:
  - orgId: 1
    name: incident-responder
    receivers:
      - uid: incident-responder-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST
policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: [alertname]
    routes:
      - receiver: incident-responder
        object_matchers:
          - [service, '=', order-tracker]
          - [alertname, '=', Order lookup server errors]
        group_wait: 5s
        group_interval: 10s
        repeat_interval: 4h
